#include <SDL.h>
#include "..\Misc\gddlist.hpp"
#include "..\Misc\logging.hpp"
#include "..\Misc\posstruct.hpp"
#include "..\Misc\actor.hpp"
class Mob;
class Player;
#include "..\Mob\Items\inv.hpp"
#include "..\Mob\destructible.hpp"
#include "..\Mob\Ai\ai.hpp"
#include "..\Mob\attack.hpp"
#include "..\Mob\Status\status.hpp"
#include "..\Mob\XP\xp.hpp"
#include "..\Mob\mob.hpp"
#include "..\Map\map.hpp"
#include "engine.hpp"
